---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: maven:3.9.5-eclipse-temurin-21-alpine
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn verify -Pcoverage -Dspring.data.mongodb.uri=mongodb://mongo:27017/blog

services:
  - name: mongo
    image: mongo:latest
