# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "prepare"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "hantsy/spring-reactive-jwt-sample"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: github
    stage: "prepare"

  setup:
      title: "Install Dependencies"
      stage: prepare
      image: 'maven:3-openjdk-17'
      working_directory: "${{clone}}"
      commands:
        - mvn dependency:go-offline -Dmaven.repo.local=/codefresh/volume/m2_repository
  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: 'maven:3-openjdk-21' # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - mvn -q verify -Pcoverage -Dspring.data.mongodb.uri=mongodb://mongo:27017/blog -Dmaven.repo.local=/codefresh/volume/m2_repository
    stage: "test"
    services:
      composition:
        mongo:
          image: mongo:latest
          ports:
            - 27017
      # readiness:
      #   timeoutSeconds: 30
      #   periodSeconds: 15
      #   image: '${{build_app_image}}'
      #   commands:
      #     - "nslookup mongo"
      #     - "nc -z mongo 27017"
        docker-engine:
          image: docker
          command: docker ps
      #    volumes: # Volumes required to run DIND and to mount your Repository
      #      - /var/run/docker.sock:/var/run/docker.sock
      #      - /var/lib/docker:/var/lib/docker
      #      - ${{CF_VOLUME_NAME}}:/codefresh/volume
  # code_coverage:
  #     title: "Code coverage"
  #     stage: test
  #     image: 'ubuntu:latest'
  #     working_directory: "${{clone}}"
  #     commands:
  #       - bash <(curl -Ls https://coverage.codacy.com/get.sh)
  #     environment:
  #       - CODACY_PROJECT_TOKEN: ${{CODACY_PROJECT_TOKEN}}
