server:
  port: 8080
spring:
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      uri: mongodb://user:secret@mongo1.example.com:12345,mongo2.example.com:23456/test
      uri: mongodb://localhost:27017/blog
      gridfs:
        database: files
        bucket: images

  webflux:
    problemdetails:
      enabled: true

jwt:
  secretKey: ecf1222c-88fd-47f3-988f-bdd78bade1ad
logging:
  level:
    root: INFO
    web: DEBUG
    com.example: DEBUG
